global:
  variant: ""
  tag: 1.22.4
  hub: registry1.dso.mil/ironbank/opensource/istio
  imagePullSecrets:
  - private-registry

istiod:
  enabled: true
  profile: ambient

ztunnel:
  profile: ambient

cni:
  profile: ambient
  imagePullSecrets:
  - private-registry
